### PR TITLE
Bug - Cloudwatch Alarm Regex Typo

### PR DESCRIPTION
**Pull request by lucasklaassen**
This PR fixes the following issue: https://github.com/sbstjn/sqs-worker-serverless/issues/2

### CODE REVIEW

**Comment by lucasklaassen** [comment]
@sbstjn any issues with merging this?

**Comment by lucasklaassen** [comment]
@sbstjn any issues with merging this?

**Comment by luanmuniz** [comment]
Had the same problem, fix the same way

**Comment by lucasklaassen** [comment]
@sbstjn the community has spoken, let's merge :)

**Pull request closed without merging**
